-- AlterEnum
ALTER TYPE "QuestionType" ADD VALUE 'CONTENT_TEXT';
ALTER TYPE "QuestionType" ADD VALUE 'CONTENT_IMAGE';
ALTER TYPE "QuestionType" ADD VALUE 'CONTENT_VIDEO';
ALTER TYPE "QuestionType" ADD VALUE 'CONTENT_INSTRUCTIONS';
ALTER TYPE "QuestionType" ADD VALUE 'CONTENT_COMPARE';
